version: 1
disable_existing_loggers: true
formatters:
  simple:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

loggers:
  papita_txnsregistrar:
    level: DEBUG
    handlers:
      - console
    propagate: no
  papita_txnsregistrar_plugins:
    level: DEBUG
    handlers:
      - console
    propagate: no
  papita_txnsmodel:
    level: DEBUG
    handlers:
      - console
    propagate: no
