# pylint: disable=C0103,W0611
"""adding user table and owner columns.

Revision ID: 06b97dfcb5c7
Revises: 53fec3d56681
Create Date: 2026-01-28 19:21:24.685129+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "06b97dfcb5c7"
down_revision: Union[str, Sequence[str], None] = "53fec3d56681"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "password_salt", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "token_salt", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_users_email"),
        "users",
        ["email"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_users_id"),
        "users",
        ["id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_users_username"),
        "users",
        ["username"],
        unique=False,
        schema="papita_transactions",
    )
    op.add_column(
        "accounts",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_accounts_owner_id"),
        "accounts",
        ["owner_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_foreign_key(
        None,
        "accounts",
        "users",
        ["owner_id"],
        ["id"],
        source_schema="papita_transactions",
        referent_schema="papita_transactions",
    )
    op.add_column(
        "accounts_indexer",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_accounts_indexer_owner_id"),
        "accounts_indexer",
        ["owner_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_accounts_indexer_type_id"),
        "accounts_indexer",
        ["type_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_foreign_key(
        None,
        "accounts_indexer",
        "users",
        ["owner_id"],
        ["id"],
        source_schema="papita_transactions",
        referent_schema="papita_transactions",
    )
    op.add_column(
        "assets_accounts",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_assets_accounts_owner_id"),
        "assets_accounts",
        ["owner_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_foreign_key(
        None,
        "assets_accounts",
        "users",
        ["owner_id"],
        ["id"],
        source_schema="papita_transactions",
        referent_schema="papita_transactions",
    )
    op.add_column(
        "bank_credit_liability_accounts",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        schema="papita_transactions",
    )
    op.create_foreign_key(
        None,
        "bank_credit_liability_accounts",
        "users",
        ["owner_id"],
        ["id"],
        source_schema="papita_transactions",
        referent_schema="papita_transactions",
    )
    op.add_column(
        "banking_asset_accounts",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        schema="papita_transactions",
    )
    op.create_foreign_key(
        None,
        "banking_asset_accounts",
        "users",
        ["owner_id"],
        ["id"],
        source_schema="papita_transactions",
        referent_schema="papita_transactions",
    )
    op.add_column(
        "credit_card_liability_accounts",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        schema="papita_transactions",
    )
    op.create_foreign_key(
        None,
        "credit_card_liability_accounts",
        "users",
        ["owner_id"],
        ["id"],
        source_schema="papita_transactions",
        referent_schema="papita_transactions",
    )
    op.add_column(
        "financed_asset_accounts",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        schema="papita_transactions",
    )
    op.create_foreign_key(
        None,
        "financed_asset_accounts",
        "users",
        ["owner_id"],
        ["id"],
        source_schema="papita_transactions",
        referent_schema="papita_transactions",
    )
    op.add_column(
        "identified_transactions",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        schema="papita_transactions",
    )
    op.create_foreign_key(
        None,
        "identified_transactions",
        "users",
        ["owner_id"],
        ["id"],
        source_schema="papita_transactions",
        referent_schema="papita_transactions",
    )
    op.add_column(
        "liability_accounts",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_liability_accounts_owner_id"),
        "liability_accounts",
        ["owner_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_foreign_key(
        None,
        "liability_accounts",
        "users",
        ["owner_id"],
        ["id"],
        source_schema="papita_transactions",
        referent_schema="papita_transactions",
    )
    op.add_column(
        "real_estate_asset_accounts",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        schema="papita_transactions",
    )
    op.create_foreign_key(
        None,
        "real_estate_asset_accounts",
        "users",
        ["owner_id"],
        ["id"],
        source_schema="papita_transactions",
        referent_schema="papita_transactions",
    )
    op.add_column(
        "trading_asset_accounts",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        schema="papita_transactions",
    )
    op.create_foreign_key(
        None,
        "trading_asset_accounts",
        "users",
        ["owner_id"],
        ["id"],
        source_schema="papita_transactions",
        referent_schema="papita_transactions",
    )
    op.add_column(
        "transactions",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_transactions_owner_id"),
        "transactions",
        ["owner_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_foreign_key(
        None,
        "transactions",
        "users",
        ["owner_id"],
        ["id"],
        source_schema="papita_transactions",
        referent_schema="papita_transactions",
    )
    op.add_column(
        "types",
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_types_owner_id"),
        "types",
        ["owner_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_foreign_key(
        None,
        "types",
        "users",
        ["owner_id"],
        ["id"],
        source_schema="papita_transactions",
        referent_schema="papita_transactions",
    )
    # ### end Alembic commands ###
    op.execute(sa.text("COMMIT"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "types", schema="papita_transactions", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_papita_transactions_types_owner_id"),
        table_name="types",
        schema="papita_transactions",
    )
    op.drop_column("types", "owner_id", schema="papita_transactions")
    op.drop_constraint(
        None, "transactions", schema="papita_transactions", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_papita_transactions_transactions_owner_id"),
        table_name="transactions",
        schema="papita_transactions",
    )
    op.drop_column("transactions", "owner_id", schema="papita_transactions")
    op.drop_constraint(
        None,
        "trading_asset_accounts",
        schema="papita_transactions",
        type_="foreignkey",
    )
    op.drop_column(
        "trading_asset_accounts", "owner_id", schema="papita_transactions"
    )
    op.drop_constraint(
        None,
        "real_estate_asset_accounts",
        schema="papita_transactions",
        type_="foreignkey",
    )
    op.drop_column(
        "real_estate_asset_accounts", "owner_id", schema="papita_transactions"
    )
    op.drop_constraint(
        None,
        "liability_accounts",
        schema="papita_transactions",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_papita_transactions_liability_accounts_owner_id"),
        table_name="liability_accounts",
        schema="papita_transactions",
    )
    op.drop_column(
        "liability_accounts", "owner_id", schema="papita_transactions"
    )
    op.drop_constraint(
        None,
        "identified_transactions",
        schema="papita_transactions",
        type_="foreignkey",
    )
    op.drop_column(
        "identified_transactions", "owner_id", schema="papita_transactions"
    )
    op.drop_constraint(
        None,
        "financed_asset_accounts",
        schema="papita_transactions",
        type_="foreignkey",
    )
    op.drop_column(
        "financed_asset_accounts", "owner_id", schema="papita_transactions"
    )
    op.drop_constraint(
        None,
        "credit_card_liability_accounts",
        schema="papita_transactions",
        type_="foreignkey",
    )
    op.drop_column(
        "credit_card_liability_accounts",
        "owner_id",
        schema="papita_transactions",
    )
    op.drop_constraint(
        None,
        "banking_asset_accounts",
        schema="papita_transactions",
        type_="foreignkey",
    )
    op.drop_column(
        "banking_asset_accounts", "owner_id", schema="papita_transactions"
    )
    op.drop_constraint(
        None,
        "bank_credit_liability_accounts",
        schema="papita_transactions",
        type_="foreignkey",
    )
    op.drop_column(
        "bank_credit_liability_accounts",
        "owner_id",
        schema="papita_transactions",
    )
    op.drop_constraint(
        None,
        "assets_accounts",
        schema="papita_transactions",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_papita_transactions_assets_accounts_owner_id"),
        table_name="assets_accounts",
        schema="papita_transactions",
    )
    op.drop_column("assets_accounts", "owner_id", schema="papita_transactions")
    op.drop_constraint(
        None,
        "accounts_indexer",
        schema="papita_transactions",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_papita_transactions_accounts_indexer_type_id"),
        table_name="accounts_indexer",
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_accounts_indexer_owner_id"),
        table_name="accounts_indexer",
        schema="papita_transactions",
    )
    op.drop_column(
        "accounts_indexer", "owner_id", schema="papita_transactions"
    )
    op.drop_constraint(
        None, "accounts", schema="papita_transactions", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_papita_transactions_accounts_owner_id"),
        table_name="accounts",
        schema="papita_transactions",
    )
    op.drop_column("accounts", "owner_id", schema="papita_transactions")
    op.drop_index(
        op.f("ix_papita_transactions_users_username"),
        table_name="users",
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_users_id"),
        table_name="users",
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_users_email"),
        table_name="users",
        schema="papita_transactions",
    )
    op.drop_table("users", schema="papita_transactions")
    # ### end Alembic commands ###
    op.execute(sa.text("COMMIT"))
