# pylint: disable=C0103,W0611
"""PPT-031 v3 seed version.

Single baseline revision for the consolidated v3 schema (11 tables).
Replaces the legacy v0 migration chain and v0→v3 backfill path.

Revision ID: a75354933e79
Revises:
Create Date: 2026-07-07 23:25:04.609257+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

from papita_txnsmodel.views import ACCOUNT_BALANCES_MATERIALIZED_VIEW

# revision identifiers, used by Alembic.
revision: str = "a75354933e79"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(sa.schema.CreateSchema("papita_transactions", if_not_exists=True))
    op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"'))
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pgcrypto"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_users_email"),
        "users",
        ["email"],
        unique=True,
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_users_id"),
        "users",
        ["id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_users_username"),
        "users",
        ["username"],
        unique=True,
        schema="papita_transactions",
    )
    op.create_table(
        "accounts",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "account_kind",
            sa.Enum(
                "CHECKING",
                "SAVINGS",
                "CASH",
                "INVESTMENT_BROKERAGE",
                "REAL_ESTATE",
                "CREDIT_CARD",
                "LOAN_MORTGAGE",
                "OTHER_ASSET",
                "OTHER_LIABILITY",
                name="account_kind",
                schema="papita_transactions",
            ),
            nullable=False,
        ),
        sa.Column(
            "ledger_side",
            sa.Enum(
                "ASSET",
                "LIABILITY",
                name="ledger_side",
                schema="papita_transactions",
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("opened_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("closed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("initial_value", sa.DECIMAL(precision=22, scale=8), nullable=True),
        sa.Column("current_value", sa.DECIMAL(precision=22, scale=8), nullable=True),
        sa.Column("current_value_as_of", sa.TIMESTAMP(), nullable=True),
        sa.Column("months_per_period", sa.SmallInteger(), nullable=True),
        sa.Column("interest_rate", sa.DECIMAL(precision=10, scale=6), nullable=True),
        sa.Column(
            "interest_rate_basis",
            sa.Enum(
                "NOMINAL_MONTHLY",
                "APY",
                name="interest_rate_basis",
                schema="papita_transactions",
            ),
            nullable=True,
        ),
        sa.Column(
            "periodic_payment",
            sa.DECIMAL(precision=22, scale=8),
            nullable=True,
        ),
        sa.Column("total_paid", sa.DECIMAL(precision=22, scale=8), nullable=True),
        sa.Column("overall_periods", sa.SmallInteger(), nullable=True),
        sa.Column("periods_paid", sa.SmallInteger(), nullable=True),
        sa.Column("closing_day", sa.SmallInteger(), nullable=True),
        sa.Column("roi", sa.DECIMAL(precision=10, scale=4), nullable=True),
        sa.Column(
            "periodic_earnings",
            sa.DECIMAL(precision=22, scale=8),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["papita_transactions.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_accounts_closed_at"),
        "accounts",
        ["closed_at"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_accounts_name"),
        "accounts",
        ["name"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_accounts_opened_at"),
        "accounts",
        ["opened_at"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_accounts_owner_id"),
        "accounts",
        ["owner_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_table(
        "categories",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "category_kind",
            sa.Enum(
                "INCOME",
                "EXPENSE",
                name="category_kind",
                schema="papita_transactions",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["papita_transactions.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["papita_transactions.categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_categories_owner_id"),
        "categories",
        ["owner_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_categories_parent_id"),
        "categories",
        ["parent_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_index(
        "uq_categories_owner_name_kind",
        "categories",
        ["owner_id", "name", "category_kind"],
        unique=True,
        schema="papita_transactions",
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "account_financing",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("asset_account_id", sa.Uuid(), nullable=False),
        sa.Column("loan_account_id", sa.Uuid(), nullable=False),
        sa.Column("financing_share", sa.DECIMAL(precision=4, scale=4), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_account_id"],
            ["papita_transactions.accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["loan_account_id"],
            ["papita_transactions.accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["papita_transactions.users.id"],
        ),
        sa.PrimaryKeyConstraint("asset_account_id", "loan_account_id"),
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_account_financing_owner_id"),
        "account_financing",
        ["owner_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_table(
        "banking_account_details",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("entity", sa.String(), nullable=False),
        sa.Column("account_number", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["papita_transactions.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
        schema="papita_transactions",
    )
    op.create_table(
        "credit_card_account_details",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("credit_limit", sa.DECIMAL(precision=22, scale=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["papita_transactions.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
        schema="papita_transactions",
    )
    op.create_table(
        "loan_account_details",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("is_paid_off", sa.Boolean(), nullable=False),
        sa.Column(
            "insurance_payment",
            sa.DECIMAL(precision=22, scale=8),
            nullable=False,
        ),
        sa.Column("extras_payment", sa.DECIMAL(precision=22, scale=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["papita_transactions.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
        schema="papita_transactions",
    )
    op.create_table(
        "real_estate_account_details",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("total_area", sa.DECIMAL(precision=12, scale=4), nullable=False),
        sa.Column("built_area", sa.DECIMAL(precision=12, scale=4), nullable=False),
        sa.Column(
            "area_unit",
            sa.Enum(
                "SQ_MT",
                "SQ_FT",
                "AC",
                "HA",
                "BLK",
                name="area_unit",
                schema="papita_transactions",
            ),
            nullable=False,
        ),
        sa.Column(
            "ownership",
            sa.Enum(
                "FULL",
                "PARTIAL",
                name="ownership",
                schema="papita_transactions",
            ),
            nullable=False,
        ),
        sa.Column("participation", sa.DECIMAL(precision=4, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["papita_transactions.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
        schema="papita_transactions",
    )
    op.create_table(
        "trading_account_details",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("buy_value", sa.DECIMAL(precision=22, scale=8), nullable=False),
        sa.Column("units", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["papita_transactions.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
        schema="papita_transactions",
    )
    op.create_table(
        "transaction_templates",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("planned_amount", sa.DECIMAL(precision=22, scale=8), nullable=False),
        sa.Column("planned_day", sa.SmallInteger(), nullable=False),
        sa.Column("use_month_end", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["papita_transactions.categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["papita_transactions.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_transaction_templates_category_id"),
        "transaction_templates",
        ["category_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_transaction_templates_name"),
        "transaction_templates",
        ["name"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_transaction_templates_owner_id"),
        "transaction_templates",
        ["owner_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_table(
        "transactions",
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "transaction_kind",
            sa.Enum(
                "INCOME",
                "EXPENSE",
                "TRANSFER",
                name="transaction_kind",
                schema="papita_transactions",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.DECIMAL(precision=22, scale=8), nullable=False),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("transaction_ts", sa.TIMESTAMP(), nullable=False),
        sa.Column("from_account_id", sa.Uuid(), nullable=True),
        sa.Column("to_account_id", sa.Uuid(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "CANCELLED",
                name="transaction_status",
                schema="papita_transactions",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reference_number", sa.String(length=64), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["papita_transactions.categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_account_id"],
            ["papita_transactions.accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["papita_transactions.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["papita_transactions.transaction_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_account_id"],
            ["papita_transactions.accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_transactions_owner_id"),
        "transactions",
        ["owner_id"],
        unique=False,
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_transactions_transaction_ts"),
        "transactions",
        ["transaction_ts"],
        unique=False,
        schema="papita_transactions",
    )
    # ### end Alembic commands ###
    op.execute(sa.text("""
            ALTER TABLE papita_transactions.accounts ADD CONSTRAINT accounts_ledger_side_matches_kind CHECK (
                (account_kind IN (
                    'CHECKING', 'SAVINGS', 'CASH', 'INVESTMENT_BROKERAGE', 'REAL_ESTATE', 'OTHER_ASSET'
                ) AND ledger_side = 'ASSET')
                OR (
                    account_kind IN ('CREDIT_CARD', 'LOAN_MORTGAGE', 'OTHER_LIABILITY')
                    AND ledger_side = 'LIABILITY'
                )
            )
            """))
    op.execute(sa.text("""
            ALTER TABLE papita_transactions.transactions ADD CONSTRAINT chk_transaction_kind_accounts CHECK (
                (transaction_kind = 'INCOME' AND from_account_id IS NULL AND to_account_id IS NOT NULL
                    AND category_id IS NOT NULL)
                OR (transaction_kind = 'EXPENSE' AND from_account_id IS NOT NULL AND to_account_id IS NULL
                    AND category_id IS NOT NULL)
                OR (
                    transaction_kind = 'TRANSFER'
                    AND from_account_id IS NOT NULL
                    AND to_account_id IS NOT NULL
                    AND category_id IS NULL
                    AND from_account_id <> to_account_id
                )
            )
            """))
    op.execute(sa.text("""
            ALTER TABLE papita_transactions.account_financing ADD CONSTRAINT chk_financing_share CHECK (
                financing_share > 0 AND financing_share <= 1
            )
            """))
    op.create_entity(ACCOUNT_BALANCES_MATERIALIZED_VIEW)
    op.create_index(
        "account_balances_owner_account_idx",
        "account_balances",
        ["owner_id", "account_id"],
        unique=True,
        schema="papita_transactions",
    )
    op.execute(sa.text("COMMIT"))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        "account_balances_owner_account_idx",
        table_name="account_balances",
        schema="papita_transactions",
    )
    op.drop_entity(ACCOUNT_BALANCES_MATERIALIZED_VIEW, cascade=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_papita_transactions_transactions_transaction_ts"),
        table_name="transactions",
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_transactions_owner_id"),
        table_name="transactions",
        schema="papita_transactions",
    )
    op.drop_table("transactions", schema="papita_transactions")
    op.drop_index(
        op.f("ix_papita_transactions_transaction_templates_owner_id"),
        table_name="transaction_templates",
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_transaction_templates_name"),
        table_name="transaction_templates",
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_transaction_templates_category_id"),
        table_name="transaction_templates",
        schema="papita_transactions",
    )
    op.drop_table("transaction_templates", schema="papita_transactions")
    op.drop_table("trading_account_details", schema="papita_transactions")
    op.drop_table("real_estate_account_details", schema="papita_transactions")
    op.drop_table("loan_account_details", schema="papita_transactions")
    op.drop_table("credit_card_account_details", schema="papita_transactions")
    op.drop_table("banking_account_details", schema="papita_transactions")
    op.drop_index(
        op.f("ix_papita_transactions_account_financing_owner_id"),
        table_name="account_financing",
        schema="papita_transactions",
    )
    op.drop_table("account_financing", schema="papita_transactions")
    op.execute(sa.text("DROP INDEX IF EXISTS papita_transactions.uq_categories_owner_name_kind"))
    op.drop_index(
        op.f("ix_papita_transactions_categories_parent_id"),
        table_name="categories",
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_categories_owner_id"),
        table_name="categories",
        schema="papita_transactions",
    )
    op.drop_table("categories", schema="papita_transactions")
    op.drop_index(
        op.f("ix_papita_transactions_accounts_owner_id"),
        table_name="accounts",
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_accounts_opened_at"),
        table_name="accounts",
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_accounts_name"),
        table_name="accounts",
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_accounts_closed_at"),
        table_name="accounts",
        schema="papita_transactions",
    )
    op.drop_table("accounts", schema="papita_transactions")
    op.drop_index(
        op.f("ix_papita_transactions_users_username"),
        table_name="users",
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_users_id"),
        table_name="users",
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_users_email"),
        table_name="users",
        schema="papita_transactions",
    )
    op.drop_table("users", schema="papita_transactions")
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSchema("papita_transactions", cascade=True, if_exists=True))
    op.execute(sa.text("COMMIT"))
