# pylint: disable=C0103,W0611
"""Fixing issue with user

Revision ID: ccaa69123f7e
Revises: 255bb7382571
Create Date: 2026-01-30 03:34:47.402527+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "ccaa69123f7e"
down_revision: Union[str, Sequence[str], None] = "255bb7382571"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_papita_transactions_users_email"),
        table_name="users",
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_users_email"),
        "users",
        ["email"],
        unique=True,
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_users_username"),
        table_name="users",
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_users_username"),
        "users",
        ["username"],
        unique=True,
        schema="papita_transactions",
    )
    op.drop_column("users", "password_salt", schema="papita_transactions")
    op.drop_column("users", "token_salt", schema="papita_transactions")
    # ### end Alembic commands ###
    op.execute(sa.text("COMMIT"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "token_salt", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        schema="papita_transactions",
    )
    op.add_column(
        "users",
        sa.Column(
            "password_salt", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_users_username"),
        table_name="users",
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_users_username"),
        "users",
        ["username"],
        unique=False,
        schema="papita_transactions",
    )
    op.drop_index(
        op.f("ix_papita_transactions_users_email"),
        table_name="users",
        schema="papita_transactions",
    )
    op.create_index(
        op.f("ix_papita_transactions_users_email"),
        "users",
        ["email"],
        unique=False,
        schema="papita_transactions",
    )
    # ### end Alembic commands ###

    op.execute(sa.text("COMMIT"))
