# pylint: disable=C0103,W0611
"""adding new fields.

Revision ID: 53fec3d56681
Revises: 93420bed0a90
Create Date: 2026-01-28 18:51:07.629595+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "53fec3d56681"
down_revision: Union[str, Sequence[str], None] = "93420bed0a90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "accounts",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.alter_column(
        "accounts",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
        schema="papita_transactions",
    )
    op.add_column(
        "assets_accounts",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "assets_accounts",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "bank_credit_liability_accounts",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "bank_credit_liability_accounts",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "banking_asset_accounts",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "banking_asset_accounts",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "credit_card_liability_accounts",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "credit_card_liability_accounts",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "financed_asset_accounts",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "financed_asset_accounts",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "identified_transactions",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "identified_transactions",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "liability_accounts",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "liability_accounts",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "real_estate_asset_accounts",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "real_estate_asset_accounts",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "trading_asset_accounts",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "trading_asset_accounts",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "transactions",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "transactions",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "types",
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "types",
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        schema="papita_transactions",
    )
    op.alter_column(
        "types",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
        schema="papita_transactions",
    )
    # ### end Alembic commands ###
    op.execute(sa.text("COMMIT"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "types",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        schema="papita_transactions",
    )
    op.drop_column("types", "updated_at", schema="papita_transactions")
    op.drop_column("types", "created_at", schema="papita_transactions")
    op.drop_column("transactions", "updated_at", schema="papita_transactions")
    op.drop_column("transactions", "created_at", schema="papita_transactions")
    op.drop_column(
        "trading_asset_accounts", "updated_at", schema="papita_transactions"
    )
    op.drop_column(
        "trading_asset_accounts", "created_at", schema="papita_transactions"
    )
    op.drop_column(
        "real_estate_asset_accounts",
        "updated_at",
        schema="papita_transactions",
    )
    op.drop_column(
        "real_estate_asset_accounts",
        "created_at",
        schema="papita_transactions",
    )
    op.drop_column(
        "liability_accounts", "updated_at", schema="papita_transactions"
    )
    op.drop_column(
        "liability_accounts", "created_at", schema="papita_transactions"
    )
    op.drop_column(
        "identified_transactions", "updated_at", schema="papita_transactions"
    )
    op.drop_column(
        "identified_transactions", "created_at", schema="papita_transactions"
    )
    op.drop_column(
        "financed_asset_accounts", "updated_at", schema="papita_transactions"
    )
    op.drop_column(
        "financed_asset_accounts", "created_at", schema="papita_transactions"
    )
    op.drop_column(
        "credit_card_liability_accounts",
        "updated_at",
        schema="papita_transactions",
    )
    op.drop_column(
        "credit_card_liability_accounts",
        "created_at",
        schema="papita_transactions",
    )
    op.drop_column(
        "banking_asset_accounts", "updated_at", schema="papita_transactions"
    )
    op.drop_column(
        "banking_asset_accounts", "created_at", schema="papita_transactions"
    )
    op.drop_column(
        "bank_credit_liability_accounts",
        "updated_at",
        schema="papita_transactions",
    )
    op.drop_column(
        "bank_credit_liability_accounts",
        "created_at",
        schema="papita_transactions",
    )
    op.drop_column(
        "assets_accounts", "updated_at", schema="papita_transactions"
    )
    op.drop_column(
        "assets_accounts", "created_at", schema="papita_transactions"
    )
    op.alter_column(
        "accounts",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        schema="papita_transactions",
    )
    op.drop_column("accounts", "updated_at", schema="papita_transactions")
    op.drop_column("accounts", "created_at", schema="papita_transactions")
    # ### end Alembic commands ###
    op.execute(sa.text("COMMIT"))
