# pylint: disable=C0103,W0611
"""Types update

Revision ID: 255bb7382571
Revises: 06b97dfcb5c7
Create Date: 2026-01-30 00:46:23.429217+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "255bb7382571"
down_revision: Union[str, Sequence[str], None] = "06b97dfcb5c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "types",
        "owner_id",
        existing_type=sa.UUID(),
        nullable=True,
        schema="papita_transactions",
    )
    # ### end Alembic commands ###
    op.execute(sa.text("COMMIT"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "types",
        "owner_id",
        existing_type=sa.UUID(),
        nullable=False,
        schema="papita_transactions",
    )
    # ### end Alembic commands ###

    op.execute(sa.text("COMMIT"))
