# pylint: disable=C0103,W0611
"""Symplifying

Revision ID: cf8d2b80bee2
Revises: b502adc40bc1
Create Date: 2025-09-12 00:39:30.910469+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cf8d2b80bee2"
down_revision: Union[str, Sequence[str], None] = "b502adc40bc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asset_accounts", "active", schema="papita_transactions")
    op.drop_column("asset_accounts", "deleted_at", schema="papita_transactions")
    op.drop_column(
        "bank_credit_liability_accounts",
        "active",
        schema="papita_transactions",
    )
    op.drop_column(
        "bank_credit_liability_accounts",
        "deleted_at",
        schema="papita_transactions",
    )
    op.drop_column("banking_asset_accounts", "active", schema="papita_transactions")
    op.drop_column("banking_asset_accounts", "deleted_at", schema="papita_transactions")
    op.drop_column(
        "credit_card_liability_accounts",
        "active",
        schema="papita_transactions",
    )
    op.drop_column(
        "credit_card_liability_accounts",
        "deleted_at",
        schema="papita_transactions",
    )
    op.drop_column("liability_accounts", "active", schema="papita_transactions")
    op.drop_column("liability_accounts", "deleted_at", schema="papita_transactions")
    op.drop_column("real_state_asset_accounts", "active", schema="papita_transactions")
    op.drop_column("real_state_asset_accounts", "deleted_at", schema="papita_transactions")
    op.drop_column("trading_asset_accounts", "active", schema="papita_transactions")
    op.drop_column("trading_asset_accounts", "deleted_at", schema="papita_transactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trading_asset_accounts",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        schema="papita_transactions",
    )
    op.add_column(
        "trading_asset_accounts",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "real_state_asset_accounts",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        schema="papita_transactions",
    )
    op.add_column(
        "real_state_asset_accounts",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "liability_accounts",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        schema="papita_transactions",
    )
    op.add_column(
        "liability_accounts",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "credit_card_liability_accounts",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        schema="papita_transactions",
    )
    op.add_column(
        "credit_card_liability_accounts",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "banking_asset_accounts",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        schema="papita_transactions",
    )
    op.add_column(
        "banking_asset_accounts",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "bank_credit_liability_accounts",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        schema="papita_transactions",
    )
    op.add_column(
        "bank_credit_liability_accounts",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema="papita_transactions",
    )
    op.add_column(
        "asset_accounts",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        schema="papita_transactions",
    )
    op.add_column(
        "asset_accounts",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        schema="papita_transactions",
    )
    # ### end Alembic commands ###
